### ISSUE TITLE
Capturar dados do formulário

### ISSUE THREAD

**Issue by MatheusMilanez** [MatheusMilanez/gerador-curriculo#7]
- [ ] Capturar dados do formulário

**Comment by ItaloCanturil** [comment]
Não sei como você pensa a maneira de criar issues, porém, ao ler essa eu acredito que possa ser quebrada em 3 issues diferentes, sendo elas:
- Capturar dados do formulário
- Criar pdf com dados estáticos 
- Armazenar dados no PDF

Ao meu ver seria melhor quebrar em várias issues tanto para facil entendimento, quanto para atrair mais pessoas que estejam interessadas em contribuir. Claro que essa é uma visão minha, fico a disposição de discutir, também estou interessado em contribuir no projeto.

**Comment by MatheusMilanez** [comment]
> Não sei como você pensa a maneira de criar issues, porém, ao ler essa eu acredito que possa ser quebrada em 3 issues diferentes, sendo elas:
> 
> * Capturar dados do formulário
> * Criar pdf com dados estáticos
> * Armazenar dados no PDF
> 
> Ao meu ver seria melhor quebrar em várias issues tanto para facil entendimento, quanto para atrair mais pessoas que estejam interessadas em contribuir. Claro que essa é uma visão minha, fico a disposição de discutir, também estou interessado em contribuir no projeto.

Fala Italo , 
Concordo plenamente com a sua visão sobre a criação das issues. Acho que dividir a tarefa em várias issues pode realmente facilitar o entendimento e tornar o processo de contribuição mais eficiente.
